# Generated by Django 3.2 on 2021-05-03 12:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration', models.PositiveSmallIntegerField()),
                ('upload_at', models.DateTimeField(default=datetime.datetime(2021, 5, 3, 12, 51, 24, 968214, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveSmallIntegerField()),
                ('upload_at', models.DateTimeField(default=datetime.datetime(2021, 5, 3, 12, 51, 24, 967214, tzinfo=utc))),
                ('host', models.CharField(max_length=100)),
                ('participant', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveSmallIntegerField()),
                ('upload_at', models.DateTimeField(default=datetime.datetime(2021, 5, 3, 12, 51, 24, 967214, tzinfo=utc))),
            ],
        ),
    ]
